# ID Permanence Configuration
# ----------------------------
# Operation: ENCRYPT or DECRYPT
operation=DECRYPT

# Secret Key for AES encryption
secretKey=wso2

# The value to encrypt or decrypt
value=Xio2Vcmt-113qdseTWpqRw
