# ID Permanence Configuration
# ----------------------------
# Operation: ENCRYPT or DECRYPT
operation=ENCRYPT

# Secret Key for AES encryption
secretKey=wso2

# The value to encrypt or decrypt
value=test-account-123
