# ID Permanence Configuration
# ----------------------------
# Operation: ENCRYPT or DECRYPT
operation=DECRYPT

# Secret Key for AES encryption
secretKey=wso2

# The value to encrypt or decrypt
value=HhW9XKBC5GWq7utLsF3W5L3vU31yMuwStl9i-nVnrFM
